### ISSUE TITLE
Error in downloading

### ISSUE THREAD

**Issue by sivannavis** [l3das/L3DAS23#2]
Hi, when I run the command, there's an error running `merge_train360`
```
Traceback (most recent call last):
  File "download_dataset.py", line 107, in <module>
    merge_train360(part1_path, part2_path)
  File "download_dataset.py", line 51, in merge_train360
    data1_c = os.listdir(data1_p)
FileNotFoundError: [Errno 2] No such file or directory: '/dlbimg/l3das/L3DAS23_Task1_train_360_part1/L3DAS23_Task1_train_360_part1/data'
```

**Comment by sivannavis** [comment]
Turns out it's related to kaggle api. Placing it in the right place solved it.
